In [6]:
import pandas as pd

In [7]:
data = pd.read_excel('최종 수정본.xlsx')
data

        Day           단어                     뜻  외움 Unnamed: 4
0      day1       resume                   이력서 NaN        NaN
1      day1    applicant              지원자, 신청자 NaN        NaN
2      day1  requirement              필요조건, 요건 NaN        NaN
3      day1         meet       (필요,요구 등을)만족시키다 NaN        NaN
4      day1    qualified             자격있는, 적격의 NaN        NaN
...     ...          ...                   ...  ..        ...
1217  day30       induce                  유발하다 NaN        NaN
1218  day30    insurance                    보험 NaN        NaN
1219  day30    nutrition                    영양 NaN        NaN
1220  day30   prevention                    예방 NaN        NaN
1221  day30  susceptible  ~에 감염되기 쉬운, 영향 받기 쉬운 NaN        NaN

[1222 rows x 5 columns]

In [8]:
# data[["단어", "뜻"]][data["Day"] == "day3"].to_csv("C:/Users/scott/OneDrive - 우송대학교(WOOSONG UNIVERSITY)/학교파일/2023 2학기/컴퓨팅사고/Baloham/QWQ vocab data/day 3.csv")

In [9]:
for i in range(1, 31):
    data[["단어","뜻"]][data["Day"] == f"day{i}"].to_csv(f"QWQ vocab data/day {i}.csv")